# Generated by Django 6.1 on 2026-08-26 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NetworkBackend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cursa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(default='Activ', max_length=20)),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NetworkBackend.train')),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_time', models.TimeField(blank=True, null=True)),
                ('departure_time', models.TimeField(blank=True, null=True)),
                ('sequence_number', models.PositiveIntegerField()),
                ('delay_minutes', models.PositiveIntegerField(default=0)),
                ('cursa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NetworkBackend.cursa')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NetworkBackend.station')),
            ],
            options={
                'ordering': ['cursa', 'sequence_number'],
            },
        ),
    ]
